# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cbd01bb286eefcac5b3cf342d9ffb9ad829014f5c8317165e18309c095994e5f486059b674ed31a1d0a9f1507cfe1c4b2bb7aa9a2deb898cebb0e75e42ccd0e

test:
  secret_key_base: 15eefe8a087479ae292671ed0f7349407ea6a7e6fb30e91e974d18396c9637e7f158e97e2463c9133eefddc6ef17d063f547a8d37aa317604089d8d3fa53876b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
